name: setlist
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  firebase_core: ^2.31.1
  flutter_bloc: ^8.1.6
  auto_route: ^8.1.3
  firebase_database: ^10.5.7
  json_annotation: ^4.9.0
  firebase_database_mocks: ^0.6.1
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
